version: '3.8'

services:
  # mongo:
  #   image: mongo
  #   container_name: mongo
  #   ports:
  #     - '27017:27017'
  #   volumes:
  #     - mongo-data:/data/db

  chromadb:
    image: ghcr.io/chroma-core/chroma:latest
    container_name: chromadb
    ports:
      - '8000:8000'

  node-app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: node-app
    ports:
      - '3000:3000'
    depends_on:
      # - mongo
      - chromadb  # Ajout ici pour dépendance
    volumes:
      - ../:/app
    working_dir: /app
    environment:
      # - MONGO_URL=mongodb://mongo:27017/ecommerce
      - CHROMA_URL=http://chromadb:8000
